name: Dispatch website event
on:
  workflow_dispatch:
jobs:
  trigger-website:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCHTOKEN }}
          repository: sampleenvironment/secop-site
          event-type: spec-update

